project_id = "pplaglcevtvlpzdnmvqd"

[functions.mercadopago-create-payment]
verify_jwt = true

[functions.mercadopago-create-dynamic-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-test-connection]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = false

[functions.check-payment-polling]
verify_jwt = false